version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pharmacy_postgres
    environment:
      POSTGRES_DB: pharmacy_db
      POSTGRES_USER: pharmacy_user
      POSTGRES_PASSWORD: postgre
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pharmacy_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pharmacy_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pharmacy.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - pharmacy_network

volumes:
  postgres_data:

networks:
  pharmacy_network:
    driver: bridge